# Generated by Django 4.2.6 on 2025-06-23 04:30

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス')),
                ('role', models.CharField(choices=[('admin', '管理者'), ('editor', '編集者'), ('author', '投稿者'), ('reader', '読者')], default='reader', max_length=10, verbose_name='権限')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='自己紹介')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='アバター')),
                ('website', models.URLField(blank=True, verbose_name='ウェブサイト')),
                ('twitter', models.CharField(blank=True, max_length=50, verbose_name='Twitter')),
                ('github', models.CharField(blank=True, max_length=50, verbose_name='GitHub')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='メール認証済み')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'ユーザー',
                'verbose_name_plural': 'ユーザー',
                'db_table': 'accounts_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='生年月日')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話番号')),
                ('address', models.TextField(blank=True, verbose_name='住所')),
                ('notification_email', models.BooleanField(default=True, verbose_name='メール通知')),
                ('notification_push', models.BooleanField(default=True, verbose_name='プッシュ通知')),
                ('privacy_public_profile', models.BooleanField(default=True, verbose_name='プロフィール公開')),
                ('privacy_show_email', models.BooleanField(default=False, verbose_name='メールアドレス公開')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ユーザープロフィール',
                'verbose_name_plural': 'ユーザープロフィール',
                'db_table': 'accounts_user_profile',
            },
        ),
    ]
