# Generated by Django 4.2.6 on 2025-07-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', '管理者'), ('editor', '編集者'), ('author', '投稿者')], default='author', max_length=10, verbose_name='権限'),
        ),
    ]
