# Generated by Django 4.2.6 on 2025-07-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_reader_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', '管理者'), ('editor', '編集者')], default='editor', max_length=10, verbose_name='権限'),
        ),
    ]
