# Generated by Django 4.2.6 on 2025-06-23 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='タグ名')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='スラグ')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('color', models.CharField(default='#6c757d', max_length=7, verbose_name='カラーコード')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': 'タグ',
                'verbose_name_plural': 'タグ',
                'db_table': 'blog_tag',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='カテゴリ名')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='スラグ')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='カラーコード')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blog.category', verbose_name='親カテゴリ')),
            ],
            options={
                'verbose_name': 'カテゴリ',
                'verbose_name_plural': 'カテゴリ',
                'db_table': 'blog_category',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='スラグ')),
                ('excerpt', models.TextField(blank=True, max_length=300, verbose_name='要約')),
                ('content', models.TextField(verbose_name='本文')),
                ('status', models.CharField(choices=[('draft', '下書き'), ('published', '公開'), ('private', '非公開'), ('scheduled', '予約投稿')], default='draft', max_length=20, verbose_name='状態')),
                ('meta_title', models.CharField(blank=True, max_length=60, verbose_name='メタタイトル')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='メタディスクリプション')),
                ('og_title', models.CharField(blank=True, max_length=60, verbose_name='OGタイトル')),
                ('og_description', models.CharField(blank=True, max_length=160, verbose_name='OGディスクリプション')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='og_images/', verbose_name='OG画像')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='アイキャッチ画像')),
                ('featured_image_alt', models.CharField(blank=True, max_length=100, verbose_name='アイキャッチ画像alt')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='表示回数')),
                ('like_count', models.PositiveIntegerField(default=0, verbose_name='いいね数')),
                ('share_count', models.PositiveIntegerField(default=0, verbose_name='シェア数')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='公開日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('allow_comments', models.BooleanField(default=True, verbose_name='コメント許可')),
                ('is_featured', models.BooleanField(default=False, verbose_name='注目記事')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='ピン留め')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='著者')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='blog.category', verbose_name='カテゴリ')),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='blog.tag', verbose_name='タグ')),
            ],
            options={
                'verbose_name': '記事',
                'verbose_name_plural': '記事',
                'db_table': 'blog_article',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IPアドレス')),
                ('user_agent', models.TextField(blank=True, verbose_name='ユーザーエージェント')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='blog.article')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '記事閲覧',
                'verbose_name_plural': '記事閲覧',
                'db_table': 'blog_article_view',
                'indexes': [models.Index(fields=['article', 'created_at'], name='blog_articl_article_a16081_idx')],
            },
        ),
        migrations.CreateModel(
            name='ArticleLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='blog.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '記事いいね',
                'verbose_name_plural': '記事いいね',
                'db_table': 'blog_article_like',
                'unique_together': {('article', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status', 'published_at'], name='blog_articl_status_8b18ca_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['author', 'status'], name='blog_articl_author__00152e_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['category', 'status'], name='blog_articl_categor_ff847e_idx'),
        ),
    ]
