# Generated by Django 4.2.6 on 2025-06-23 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='コメント内容')),
                ('is_approved', models.BooleanField(default=False, verbose_name='承認済み')),
                ('is_spam', models.BooleanField(default=False, verbose_name='スパム')),
                ('is_edited', models.BooleanField(default=False, verbose_name='編集済み')),
                ('like_count', models.PositiveIntegerField(default=0, verbose_name='いいね数')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IPアドレス')),
                ('user_agent', models.TextField(blank=True, verbose_name='ユーザーエージェント')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='編集日時')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.article', verbose_name='記事')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comments.comment', verbose_name='親コメント')),
            ],
            options={
                'verbose_name': 'コメント',
                'verbose_name_plural': 'コメント',
                'db_table': 'comments_comment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approved', '承認'), ('rejected', '拒否'), ('deleted', '削除'), ('marked_spam', 'スパムマーク'), ('unmarked_spam', 'スパム解除'), ('edited', '編集')], max_length=20, verbose_name='アクション')),
                ('reason', models.TextField(blank=True, verbose_name='理由')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='実行日時')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_logs', to='comments.comment')),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'コメント管理ログ',
                'verbose_name_plural': 'コメント管理ログ',
                'db_table': 'comments_moderation_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'スパム'), ('inappropriate', '不適切な内容'), ('harassment', 'ハラスメント'), ('copyright', '著作権侵害'), ('other', 'その他')], max_length=20, verbose_name='報告理由')),
                ('description', models.TextField(blank=True, verbose_name='詳細')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='解決済み')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解決日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='報告日時')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='comments.comment')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'コメント報告',
                'verbose_name_plural': 'コメント報告',
                'db_table': 'comments_comment_report',
                'unique_together': {('comment', 'reporter')},
            },
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='comments.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'コメントいいね',
                'verbose_name_plural': 'コメントいいね',
                'db_table': 'comments_comment_like',
                'unique_together': {('comment', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['article', 'is_approved'], name='comments_co_article_f61045_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent', 'created_at'], name='comments_co_parent__10bc81_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author', 'created_at'], name='comments_co_author__a235af_idx'),
        ),
    ]
